[package]
name = "vitium-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.194"
serde_json = "1.0.111"
vitium-common = { path = "../common" }

[lib]
crate_type = ["staticlib"]
