"$schema" = "https://schema.tauri.app/config/2.0.0"
productName = "vitium-client"
version = "0.1.0"
identifier = "com.vitium-client.app"

[build]
beforeBuildCommand = "pnpm build"
frontendDist = "../src"

[app]
withGlobalTauri = true
security.assetProtocol.enable = true
security.assetProtocol.scope = ["**"]

[[app.windows]]
title = "Vitium"
width = 800
height = 600
decorations = false
minWidth = 400
minHeight = 300

[bundle]
active = false
# targets = "none"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
