[package]
name = "vitium-common-cfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vitium-common = { path = "../common" }

[lib]
crate_type = ["staticlib"]

[workspace]
