[package]
name = "vitium-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndm = "0.9.10"
postcard = "1.0.8"
serde = "1.0.193"
serde_derive = "1.0.193"
serde_json = "1.0.110"
toml = "0.8.8"
