use serde_derive::{Deserialize, Serialize};

/// A story message generated by server's actions.
#[derive(Serialize, Deserialize, Clone)]
pub struct Record {
    pub turn: i128,
    pub text: String,
}
