name: Next.js NPM Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  npm-checks:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]  # You can add more versions if needed: [16.x, 18.x, 20.x]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
        
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
        
    - name: Build WASM package
      working-directory: ./api
      run: wasm-pack build
    
    - name: Install dependencies
      working-directory: ./client
      run: npm ci
      
    - name: Check for outdated packages
      working-directory: ./client
      run: npm outdated || true  # "|| true" ensures workflow doesn't fail at this step
    
    - name: Run linting
      working-directory: ./client
      run: npm run lint
      
    - name: Type checking
      working-directory: ./client
      run: npm run type-check || npm run check-types || echo "No type checking script found"
    
    # - name: Run tests
    #   working-directory: ./client
    #   run: npm test
      
    - name: Build project
      working-directory: ./client
      run: npm run build
