name: Vitium core crates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile crates
      run: cargo build
    - name: Upload vitium-common build
      uses: actions/upload-artifact@v3
      with:
          name: vitium-common
          path: target/debug/libvitium_common.rlib
    - name: Upload vitium-server build
      uses: actions/upload-artifact@v3
      with:
          name: vitium-server
          path: target/debug/vitium-server
